export const mangaRoute = ["Manga Details", "Manga"]

export const MangaType = ["newest", "latest", "topview"];

export const MangaState = ["all", "Completed", "Ongoing", "drop", "unknown"];

export const MangaCategory = [
  "ALL",
  "Action",
  "Adventure",
  "Comedy",
  "Cooking",
  "Doujinshi",
  "Drama",
  "Erotica",
  "Fantasy",
  "Gender bender",
  "Harem",
  "Historical",
  "Horror",
  "Isekai",
  "Josei",
  "Manhua",
  "Manhwa",
  "Martial arts",
  "Mature",
  "Mecha",
  "Medical",
  "Mystery",
  "One shot",
  "Pornographic",
  "Psychological",
  "Romance",
  "School life",
  "Sci fi",
  "Seinen",
  "Shoujo",
  "Shoujo ai",
  "Shounen",
  "Shounen ai",
  "Slice of life",
  "Smut",
  "Sports",
  "Supernatural",
  "Tragedy",
  "Webtoons",
  "Yaoi",
  "Yuri",
];
